services:
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Zurich
    volumes:
      - /mnt/docker/_swarm_configs/tautulli:/config
    ports:
      - 8181:8181
    deploy:
      placement:
        constraints: [node.role == worker]
