services:
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    deploy:
      placement:
        constraints: [node.role == worker]
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Zurich
    volumes:
      - /mnt/docker/_swarm_configs/overseerr:/config
    ports:
      - 5055:5055
