services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    deploy:
      placement:
        constraints: [node.role == worker]
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Zurich
    volumes:
      - /mnt/docker/_swarm_configs/prowlarr:/config
    ports:
      - 9696:9696
