services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    deploy:
      mode: global
      placement:
        constraints: [node.role == worker]
      labels:
        com.centurylinklabs.watchtower.enable: "true"
    command: tunnel --no-autoupdate run --token
      ${TOKEN} #secrets
